[project]
name = "langchain-py-tutorials"
version = "0.1.0"
description = "LangChain python tutorials"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.2.0",
    "langchain[anthropic]>=1.2.0",
    "ipywidgets>=8.1.7",
    "jupyterlab>=4.5.1"]
