[project]
name = "langchain-py-tutorials"
version = "0.2.0"
description = "LangChain (Python) tutorials"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.2.0",
    "langchain[anthropic]>=1.2.0",
    "ipykernel>=7.1.0"
]
